package com.senpro.entity;

// Generated Nov 15, 2017 12:32:11 AM by Hibernate Tools 3.4.0.CR1



import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

import com.senpro.utils.InventoryConstants;

/**
 * EventDetailTable generated by hbm2java
 */


@NamedQueries(  
	    {  
	        @NamedQuery(  
	        name = InventoryConstants.NAMED_QUERY_deleteRecordById,  
	        query = "delete EventDetailTable  where id = :id"  
	        )  
	    }  
	)  


@Entity
@Table(name = "EventDetailTable", catalog = "Events")
public class EventDetailTable implements java.io.Serializable {

	private Integer eventId;
	private String eventTitle;
	private String eventDate;
	private Integer eventStartTime;
	private Integer eventEndTime;
	private BigDecimal ticketPrice;
	private int nbrOfTicketsLeft;
	private String description;
	private String imagePath;

	public EventDetailTable() {
	}

	public EventDetailTable(BigDecimal ticketPrice, int nbrOfTicketsLeft) {
		this.ticketPrice = ticketPrice;
		this.nbrOfTicketsLeft = nbrOfTicketsLeft;
	}

	public EventDetailTable(String eventTitle, String eventDate,
			Integer eventStartTime, Integer eventEndTime,
			BigDecimal ticketPrice, int nbrOfTicketsLeft, String description,
			String imagePath) {
		this.eventTitle = eventTitle;
		this.eventDate = eventDate;
		this.eventStartTime = eventStartTime;
		this.eventEndTime = eventEndTime;
		this.ticketPrice = ticketPrice;
		this.nbrOfTicketsLeft = nbrOfTicketsLeft;
		this.description = description;
		this.imagePath = imagePath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "eventID", unique = true, nullable = false)
	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	@Column(name = "eventTitle", length = 65535)
	public String getEventTitle() {
		return this.eventTitle;
	}

	public void setEventTitle(String eventTitle) {
		this.eventTitle = eventTitle;
	}

	@Column(name = "eventDate", length = 10)
	public String getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(String eventDate) {
		this.eventDate = eventDate;
	}

	@Column(name = "eventStartTime")
	public Integer getEventStartTime() {
		return this.eventStartTime;
	}

	public void setEventStartTime(Integer eventStartTime) {
		this.eventStartTime = eventStartTime;
	}

	@Column(name = "eventEndTime")
	public Integer getEventEndTime() {
		return this.eventEndTime;
	}

	public void setEventEndTime(Integer eventEndTime) {
		this.eventEndTime = eventEndTime;
	}

	@Column(name = "ticketPrice", nullable = false, precision = 6)
	public BigDecimal getTicketPrice() {
		return this.ticketPrice;
	}

	public void setTicketPrice(BigDecimal ticketPrice) {
		this.ticketPrice = ticketPrice;
	}

	@Column(name = "nbrOfTicketsLeft", nullable = false)
	public int getNbrOfTicketsLeft() {
		return this.nbrOfTicketsLeft;
	}

	public void setNbrOfTicketsLeft(int nbrOfTicketsLeft) {
		this.nbrOfTicketsLeft = nbrOfTicketsLeft;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "imagePath", length = 60)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

}
